In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn
%matplotlib inline

Mounted at /content/drive

In [ ]:
from datetime import datetime

In [ ]:
sales_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/sales_data.csv')

In [ ]:
sales_data.head()

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Price,Unit Cost
0,SO - 000101,In-Store,WARE-UHY1004,12/31/2017,5/31/2018,6/14/2018,6/19/2018,USD,6,15,259,12,5,0.075,1963.1,1001.181
1,SO - 000102,Online,WARE-NMK1003,12/31/2017,5/31/2018,6/22/2018,7/2/2018,USD,14,20,196,27,3,0.075,3939.6,3348.660
2,SO - 000103,Distributor,WARE-UHY1004,12/31/2017,5/31/2018,6/21/2018,7/1/2018,USD,21,16,213,16,1,0.050,1775.5,781.220
3,SO - 000104,Wholesale,WARE-NMK1003,12/31/2017,5/31/2018,6/2/2018,6/7/2018,USD,28,48,107,23,8,0.075,2324.9,1464.687
4,SO - 000105,Distributor,WARE-NMK1003,4/10/2018,5/31/2018,6/16/2018,6/26/2018,USD,22,49,111,26,8,0.100,1822.4,1476.144

In [ ]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7991 entries, 0 to 7990
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OrderNumber       7991 non-null   object
 1   Sales Channel     7991 non-null   object
 2   WarehouseCode     7991 non-null   object
 3   ProcuredDate      7991 non-null   object
 4   OrderDate         7991 non-null   object
 5   ShipDate          7991 non-null   object
 6   DeliveryDate      7991 non-null   object
 7   CurrencyCode      7991 non-null   object
 8   _SalesTeamID      7991 non-null   int64
 9   _CustomerID       7991 non-null   int64
 10  _StoreID          7991 non-null   int64
 11  _ProductID        7991 non-null   int64
 12  Order Quantity    7991 non-null   int64
 13  Discount Applied  7991 non-null   float64
 14  Unit Price        7991 non-null   float64
 15  Unit Cost         7991 non-null   float64
dtypes: float64(3), int64(5), object(8)
memory usage: 999.0+ KB

In [ ]:
sales_data.describe()

,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Price,Unit Cost
count,7991.000000,7991.000000,7991.000000,7991.000000,7991.000000,7991.000000,7991.000000,7991.000000
mean,14.384307,25.457014,183.850081,23.771743,4.525341,0.114394,2284.536504,1431.911054
std,7.986086,14.414883,105.903946,13.526545,2.312631,0.085570,1673.096364,1112.413043
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.050000,167.500000,68.675000
25%,8.000000,13.000000,91.000000,12.000000,3.000000,0.050000,1031.800000,606.115500
50%,14.000000,25.000000,183.000000,24.000000,5.000000,0.075000,1849.200000,1080.576000
75%,21.000000,38.000000,276.000000,36.000000,7.000000,0.150000,3611.300000,2040.250500
max,28.000000,50.000000,367.000000,47.000000,8.000000,0.400000,6566.000000,5498.556000

In [ ]:
missing_values=sales_data.isnull().sum()
percent_missing = sales_data.isnull().sum()/sales_data.shape[0]*100

value = {
    'missing_values':missing_values,
    'percent_missing':percent_missing
}
frame=pd.DataFrame(value)
frame

                  missing_values  percent_missing
OrderNumber                    0              0.0
Sales Channel                  0              0.0
WarehouseCode                  0              0.0
ProcuredDate                   0              0.0
OrderDate                      0              0.0
ShipDate                       0              0.0
DeliveryDate                   0              0.0
CurrencyCode                   0              0.0
_SalesTeamID                   0              0.0
_CustomerID                    0              0.0
_StoreID                       0              0.0
_ProductID                     0              0.0
Order Quantity                 0              0.0
Discount Applied               0              0.0
Unit Price                     0              0.0
Unit Cost                      0              0.0

In [ ]:
df = sales_data.copy()

In [ ]:
df['revenue'] = (df['Unit Price'] -(df['Unit Price'] * df['Discount Applied']) -df['Unit Cost']) * df['Order Quantity']

In [ ]:
df['revenue']

0       4073.4325
1        886.4100
2        905.5050
3       5486.7640
4       1312.1280
          ...
7986      94.9725
7987    6725.4600
7988    1338.9950
7989    1286.4000
7990    3371.7750
Name: revenue, Length: 7991, dtype: float64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7991 entries, 0 to 7990
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OrderNumber       7991 non-null   object
 1   Sales Channel     7991 non-null   object
 2   WarehouseCode     7991 non-null   object
 3   ProcuredDate      7991 non-null   object
 4   OrderDate         7991 non-null   object
 5   ShipDate          7991 non-null   object
 6   DeliveryDate      7991 non-null   object
 7   CurrencyCode      7991 non-null   object
 8   _SalesTeamID      7991 non-null   int64
 9   _CustomerID       7991 non-null   int64
 10  _StoreID          7991 non-null   int64
 11  _ProductID        7991 non-null   int64
 12  Order Quantity    7991 non-null   int64
 13  Discount Applied  7991 non-null   float64
 14  Unit Price        7991 non-null   float64
 15  Unit Cost         7991 non-null   float64
 16  revenue           7991 non-null   float64
dtypes: float64(4), int64(5), object(8)
memory usage: 1.0+ MB

In [ ]:
df['_CustomerID'] = df['_CustomerID'].apply(str)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7991 entries, 0 to 7990
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OrderNumber       7991 non-null   object
 1   Sales Channel     7991 non-null   object
 2   WarehouseCode     7991 non-null   object
 3   ProcuredDate      7991 non-null   object
 4   OrderDate         7991 non-null   object
 5   ShipDate          7991 non-null   object
 6   DeliveryDate      7991 non-null   object
 7   CurrencyCode      7991 non-null   object
 8   _SalesTeamID      7991 non-null   int64
 9   _CustomerID       7991 non-null   object
 10  _StoreID          7991 non-null   int64
 11  _ProductID        7991 non-null   int64
 12  Order Quantity    7991 non-null   int64
 13  Discount Applied  7991 non-null   float64
 14  Unit Price        7991 non-null   float64
 15  Unit Cost         7991 non-null   float64
 16  revenue           7991 non-null   float64
dtypes: float64(4), int64(4), object(9)
memory usage: 1.0+ MB

In [ ]:
columns = ['OrderNumber', '_CustomerID', 'OrderDate' , 'revenue']
df_dataset = df[columns]

In [ ]:
today_date = pd.to_datetime('2023-11-17')

In [ ]:
df_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7991 entries, 0 to 7990
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderNumber  7991 non-null   object
 1   _CustomerID  7991 non-null   object
 2   OrderDate    7991 non-null   object
 3   revenue      7991 non-null   float64
dtypes: float64(1), object(3)
memory usage: 249.8+ KB

In [ ]:
df_dataset['OrderDate'] = pd.to_datetime(df_dataset['OrderDate'])

<ipython-input-17-b419350c4957>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dataset['OrderDate'] = pd.to_datetime(df_dataset['OrderDate'])

In [ ]:
df_dataset

       OrderNumber _CustomerID  OrderDate    revenue
0      SO - 000101          15 2018-05-31  4073.4325
1      SO - 000102          20 2018-05-31   886.4100
2      SO - 000103          16 2018-05-31   905.5050
3      SO - 000104          48 2018-05-31  5486.7640
4      SO - 000105          49 2018-05-31  1312.1280
...            ...         ...        ...        ...
7986  SO - 0008087          41 2020-12-30    94.9725
7987  SO - 0008088          29 2020-12-30  6725.4600
7988  SO - 0008089          32 2020-12-30  1338.9950
7989  SO - 0008090          42 2020-12-30  1286.4000
7990  SO - 0008091          41 2020-12-30  3371.7750

[7991 rows x 4 columns]

In [ ]:
rfm_dataset = df_dataset.groupby('_CustomerID').agg({
    'OrderDate': lambda v: (today_date -v.max()).days,
    'OrderNumber': 'count',
    'revenue':'sum'
})

In [ ]:
rfm_dataset

             OrderDate  OrderNumber      revenue
_CustomerID
1                 1059          152  335933.6115
10                1065          158  435122.1870
11                1056          178  487614.2415
12                1053          210  616719.2550
13                1054          171  441003.2795
14                1055          157  381450.0280
15                1054          142  441668.3550
16                1053          135  402938.7705
17                1056          175  534027.3860
18                1056          186  451637.7540
19                1053          165  443231.8335
2                 1059          135  327409.1345
20                1059          167  439147.9490
21                1053          164  479383.0905
22                1054          140  401721.7825
23                1062          164  449782.2895
24                1073          151  352505.5255
25                1055          162  461601.9940
26                1061          153  375766.6860
27                1053          144  336959.7835
28                1058          145  348495.4750
29                1052          179  531770.6920
3                 1060          181  466220.1365
30                1054          159  442372.3910
31                1054          152  398616.8350
32                1052          173  435206.0710
33                1054          156  495444.2635
34                1065          176  496418.6780
35                1060          145  345844.5865
36                1054          156  441225.9540
37                1061          152  425241.0940
38                1058          150  350687.6480
39                1054          176  471608.1425
4                 1055          167  526981.0630
40                1059          150  406016.9180
41                1052          161  403693.2910
42                1052          161  427159.6055
43                1055          151  372471.3245
44                1053          156  348209.0500
45                1055          156  407145.0305
46                1054          157  378414.7270
47                1058          168  442845.8465
48                1060          172  424970.7490
49                1057          152  354161.3300
5                 1080          159  445632.7450
50                1066          163  498384.9940
6                 1054          143  392141.0840
7                 1053          153  414155.9775
8                 1055          142  338000.0590
9                 1058          171  500166.4570

In [ ]:
rfm_dataset.rename(
    columns={
        'OrderDate': 'recency',
        'OrderNumber': 'frequency',
        'revenue':'monetary'
    }, inplace=True)

In [ ]:
r = pd.qcut(rfm_dataset['recency'], q=5, labels=range(5,0,-1))
f = pd.qcut(rfm_dataset['frequency'], q=5, labels=range(1,6))
m = pd.qcut(rfm_dataset['monetary'], q=5, labels=range(1, 6))

In [ ]:
rfm = rfm_dataset.assign(R=r.values, F=f.values, M=m.values)

In [ ]:
print(rfm)

             recency  frequency     monetary  R  F  M
_CustomerID
1               1059        152  335933.6115  2  2  1
10              1065        158  435122.1870  1  3  3
11              1056        178  487614.2415  3  5  5
12              1053        210  616719.2550  5  5  5
13              1054        171  441003.2795  4  4  3
14              1055        157  381450.0280  3  3  2
15              1054        142  441668.3550  4  1  4
16              1053        135  402938.7705  5  1  2
17              1056        175  534027.3860  3  5  5
18              1056        186  451637.7540  3  5  4
19              1053        165  443231.8335  5  4  4
2               1059        135  327409.1345  2  1  1
20              1059        167  439147.9490  2  4  3
21              1053        164  479383.0905  5  4  5
22              1054        140  401721.7825  4  1  2
23              1062        164  449782.2895  1  4  4
24              1073        151  352505.5255  1  2  1
25              1055        162  461601.9940  3  4  4
26              1061        153  375766.6860  1  2  2
27              1053        144  336959.7835  5  1  1
28              1058        145  348495.4750  2  1  1
29              1052        179  531770.6920  5  5  5
3               1060        181  466220.1365  2  5  4
30              1054        159  442372.3910  4  3  4
31              1054        152  398616.8350  4  2  2
32              1052        173  435206.0710  5  5  3
33              1054        156  495444.2635  4  2  5
34              1065        176  496418.6780  1  5  5
35              1060        145  345844.5865  2  1  1
36              1054        156  441225.9540  4  2  3
37              1061        152  425241.0940  1  2  3
38              1058        150  350687.6480  2  1  1
39              1054        176  471608.1425  4  5  4
4               1055        167  526981.0630  3  4  5
40              1059        150  406016.9180  2  1  2
41              1052        161  403693.2910  5  3  2
42              1052        161  427159.6055  5  3  3
43              1055        151  372471.3245  3  2  2
44              1053        156  348209.0500  5  2  1
45              1055        156  407145.0305  3  2  3
46              1054        157  378414.7270  4  3  2
47              1058        168  442845.8465  2  4  4
48              1060        172  424970.7490  2  5  3
49              1057        152  354161.3300  2  2  1
5               1080        159  445632.7450  1  3  4
50              1066        163  498384.9940  1  4  5
6               1054        143  392141.0840  4  1  2
7               1053        153  414155.9775  5  2  3
8               1055        142  338000.0590  3  1  1
9               1058        171  500166.4570  2  4  5